services:
  next-intl-auth:
    build:
      context: ../../
      dockerfile: docker/production/Dockerfile
      cache_from:
        - next-intl-auth:latest
    image: next-intl-auth
    restart: always
    ports:
      - "127.0.0.1:3000:3000"
    env_file:
      - ../../.env.production
